// Automatically generated by the res2go IDE plug-in.
package main

import (
	"log"

	"./ui"

	"github.com/ying32/govcl/vcl"
)

func main() {
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)
	vcl.Application.SetScaled(true)
	vcl.Application.SetTitle("codegen")
	vcl.Application.Initialize()
	vcl.Application.SetMainFormOnTaskBar(true)
	vcl.Application.CreateForm(&ui.FrmMain)
	vcl.Application.Run()
}
